### ISSUE TITLE
Model issue

### ISSUE THREAD

**Issue by tcantrell** [IamPerek/prk-fivem-appearance#3]
Line is throwing errors upon attempt to create new charc.   

cb(PlayerData.skin, PlayerData.model.model

**Comment by IamPerek** [comment]
> 

maybe thats because you need to add the ensure and setr under everything like these: # QBCore & SMRP #

ensure something
ensure something
ensure something
ensure something
ensure something
ensure something

# fivem-appearance
setr fivem-appearance:locale "en"
ensure fivem-appearance

**Comment by tcantrell** [comment]
Its the updated qb-core that's not compatible. It worked fine with older version, so I have no clue what the deal is.

**Comment by tcantrell** [comment]
Was a clothing mp_ override issue. My fault, thanks anyways.

**Comment by IamPerek** [comment]
> Was a clothing mp_ override issue. My fault, thanks anyways.

okay no problem but everything works fine?
